import { Inter } from "next/font/google";
import "./globals.css";
import ClientLoader from "./clientloader";

export const metadata = {
  title: "Law Office Of Udo Uchenna Ekekeulu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLoader>
          {children}
        </ClientLoader>
      </body>
    </html>
  );
}
